### ISSUE TITLE
[Bug]: 安装时报除0错误

### ISSUE THREAD

**Issue by c-doubley** [secretflow/spu#778] opened 2024-07-19 03:27 UTC
### Issue Type

Build/Install

### Modules Involved

Others

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

spu 0.9.1

### OS Platform and Distribution

linux ubuntu 22.04

### Python Version

3.10

### Current Behavior?

在通过源码安装时，运行指令python setup.py bdist_wheel出现除数不能为0的报错
external/yacl/yacl/base/dynamic_bitset.h:2296:20: error: division by zero is not a constant expression
 2296 |   constexpr size_t init_val_required_blocks = u128_bits_number / bits_per_block;
      |     

### Standalone code to reproduce the issue

```Python
python setup.py bdist_wheel
```

### Relevant log output

```Shell
ERROR: /root/.cache/bazel/_bazel_root/c35ba410d78caf6851999d4e768cfb03/external/yacl/yacl/crypto/rand/BUILD.bazel:19:16: Compiling yacl/crypto/rand/rand.cc failed: (Exit 1): gcc failed: error executing command (from target @yacl//yacl/crypto/rand:rand) 
  (cd /root/.cache/bazel/_bazel_root/c35ba410d78caf6851999d4e768cfb03/sandbox/processwrapper-sandbox/3860/execroot/spulib && \
  exec env - \
    BAZEL_LINKLIBS=-l%:libstdc++.a:-l%:libgcc.a \
    BAZEL_LINKOPTS=-static-libstdc++:-static-libgcc \
    PATH=/usr/local/gcc-11.2/bin:/usr/local/gcc-11.2/bin:/root/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/bin/remote-cli:/usr/local/gcc-11.2/bin:/usr/local/gcc-11.2/bin:/root/miniconda3/envs/spu/bin:/root/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++14' -MD -MF bazel-out/k8-opt/bin/external/yacl/yacl/crypto/rand/_objs/rand/rand.pic.d '-frandom-seed=bazel-out/k8-opt/bin/external/yacl/yacl/crypto/rand/_objs/rand/rand.pic.o' -fPIC -DFMT_HEADER_ONLY -DSPDLOG_FMT_EXTERNAL -DSPDLOG_NO_TLS -DMSGPACK_NO_BOOST -DBLAKE3_C_EXTERNAL '-DBAZEL_CURRENT_REPOSITORY="yacl"' -iquote external/yacl -iquote bazel-out/k8-opt/bin/external/yacl -iquote external/com_google_absl -iquote bazel-out/k8-opt/bin/external/com_google_absl -iquote external/com_github_greendow_hash_drbg -iquote bazel-out/k8-opt/bin/external/com_github_greendow_hash_drbg -iquote external/com_github_blake3team_blake3 -iquote bazel-out/k8-opt/bin/external/com_github_blake3team_blake3 -isystem bazel-out/k8-opt/bin/external/com_github_fmtlib_fmt/fmtlib/include -isystem bazel-out/k8-opt/bin/external/com_github_gabime_spdlog/spdlog/include -isystem bazel-out/k8-opt/bin/external/com_github_libtom_libtommath/libtommath/include -isystem bazel-out/k8-opt/bin/external/com_github_msgpack_msgpack/msgpack/include -isystem bazel-out/k8-opt/bin/external/com_github_google_cpu_features/cpu_features/include -isystem bazel-out/k8-opt/bin/external/com_github_openssl_openssl/openssl/include -isystem external/com_github_blake3team_blake3/include -isystem bazel-out/k8-opt/bin/external/com_github_blake3team_blake3/include '-fdiagnostics-color=always' -Wl,-z,noexecstack -fopenmp -fPIC -fstack-protector-strong -mavx -DCHECK_AVX '-std=c++17' -O2 -Wall -Wextra -Werror -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/yacl/yacl/crypto/rand/rand.cc -o bazel-out/k8-opt/bin/external/yacl/yacl/crypto/rand/_objs/rand/rand.pic.o)
# Configuration: b31970f7587b61226d79424fd913eb94a75d0bc8399da15b61f8ffd8970f060f
# Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from external/yacl/yacl/crypto/rand/rand.h:25,
                 from external/yacl/yacl/crypto/rand/rand.cc:15:
external/yacl/yacl/base/dynamic_bitset.h: In instantiation of 'constexpr yacl::dynamic_bitset<Block, Allocator>::dynamic_bitset(yacl::dynamic_bitset<Block, Allocator>::size_type, uint128_t, const allocator_type&) [with Block = __int128 unsigned; Allocator = std::allocator<__int128 unsigned>; yacl::dynamic_bitset<Block, Allocator>::size_type = long unsigned int; uint128_t = __int128 unsigned; yacl::dynamic_bitset<Block, Allocator>::allocator_type = std::allocator<__int128 unsigned>]':
external/yacl/yacl/crypto/rand/rand.cc:105:1:   required from here
external/yacl/yacl/base/dynamic_bitset.h:2296:20: error: division by zero is not a constant expression
 2296 |   constexpr size_t init_val_required_blocks = u128_bits_number / bits_per_block;
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~
INFO: Elapsed time: 226.236s, Critical Path: 144.76s
INFO: 2207 processes: 265 internal, 1942 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by wangzul** [comment] 2024-07-19 03:56
可以优先检查一下是否存在依赖缺失的问题https://www.secretflow.org.cn/zh-CN/docs/blog/latest/tox42l#qupZn

**Comment by wangzul** [comment] 2024-07-19 08:14
> 可以优先检查一下是否存在依赖缺失的问题https://www.secretflow.org.cn/zh-CN/docs/blog/latest/tox42l#qupZn

@c-doubley 请问这部分的环境依赖是否能解决你那边编译不通过的问题

**Comment by anakinxc** [comment] 2024-07-19 12:07
Duplicate of https://github.com/secretflow/yacl/issues/121

**Closed by anakinxc** 2024-07-19 12:07 UTC

**Comment by c-doubley** [comment] 2024-07-19 13:50
按照另一篇的指示 使用包管理的方式安装gcc后
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update && sudo apt install gcc-11 g++-11
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-11 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-11  --slave /usr/bin/cpp cpp /usr/bin/cpp-11;
还出现了新的问题，但是应该也是和gcc有关
ERROR: /root/.cache/bazel/_bazel_root/c35ba410d78caf6851999d4e768cfb03/external/zlib/BUILD.bazel:19:11: Compiling uncompr.c failed: undeclared inclusion(s) in rule '@zlib//:zlib':
this rule is missing dependency declarations for the following files included by 'uncompr.c':
  '/usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h'
  '/usr/lib/gcc/x86_64-linux-gnu/11/include/limits.h'
  '/usr/lib/gcc/x86_64-linux-gnu/11/include/syslimits.h'
  '/usr/lib/gcc/x86_64-linux-gnu/11/include/stdarg.h'
INFO: Elapsed time: 6.870s, Critical Path: 1.27s
INFO: 92 processes: 92 internal.
FAILED: Build did NOT complete successfully

**Comment by anakinxc** [comment] 2024-07-19 13:52
> 按照另一篇的指示 使用包管理的方式安装gcc后 sudo add-apt-repository ppa:ubuntu-toolchain-r/test sudo apt update && sudo apt install gcc-11 g++-11 sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-11 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-11 --slave /usr/bin/cpp cpp /usr/bin/cpp-11; 还出现了新的问题，但是应该也是和gcc有关 ERROR: /root/.cache/bazel/_bazel_root/c35ba410d78caf6851999d4e768cfb03/external/zlib/BUILD.bazel:19:11: Compiling uncompr.c failed: undeclared inclusion(s) in rule '@zlib//:zlib': this rule is missing dependency declarations for the following files included by 'uncompr.c': '/usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h' '/usr/lib/gcc/x86_64-linux-gnu/11/include/limits.h' '/usr/lib/gcc/x86_64-linux-gnu/11/include/syslimits.h' '/usr/lib/gcc/x86_64-linux-gnu/11/include/stdarg.h' INFO: Elapsed time: 6.870s, Critical Path: 1.27s INFO: 92 processes: 92 internal. FAILED: Build did NOT complete successfully

Please run `bezel clean --expunge`
