### ISSUE TITLE
[Bug]: 在anolis 23（centos 8) 系统下，无法编译spu

### ISSUE THREAD

**Issue by reacher1130** [secretflow/spu#904] opened 2024-11-06 02:38 UTC
### Issue Type

Build/Install

### Modules Involved

SPU compiler

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

spu 0.9.2b0

### OS Platform and Distribution

anolis os 23.1

### Python Version

3.10

### Compiler Version

gcc 版本 12.3.0 20230508 (Anolis OS 12.3.0-5) (GCC) 

### Current Behavior?

ERROR: An error occurred during the fetch of repository 'com_github_intel_ipp':
   Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/intel/ipp-crypto/archive/refs/tags/ippcp_2021.8.tar.gz] to /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/external/com_github_intel_ipp/temp10266711606055131087/ippcp_2021.8.tar.gz: Checksum was d70f42832337775edb022ca8ac1ac418f272e791ec147778ef7942aede414cdc but wanted 1ecfa70328221748ceb694debffa0106b92e0f9bf6a484f8e8512c2730c7d730
ERROR: /root/spu/WORKSPACE:32:9: fetching http_archive rule //external:com_github_intel_ipp: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/intel/ipp-crypto/archive/refs/tags/ippcp_2021.8.tar.gz] to /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/external/com_github_intel_ipp/temp10266711606055131087/ippcp_2021.8.tar.gz: Checksum was d70f42832337775edb022ca8ac1ac418f272e791ec147778ef7942aede414cdc but wanted 1ecfa70328221748ceb694debffa0106b92e0f9bf6a484f8e8512c2730c7d730
ERROR: /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/external/psi/psi/cryptor/BUILD.bazel:45:15: @psi//psi/cryptor:ipp_ecc_cryptor depends on @com_github_intel_ipp//:ipp in repository @com_github_intel_ipp which failed to fetch. no such package '@com_github_intel_ipp//': java.io.IOException: Error downloading [https://github.com/intel/ipp-crypto/archive/refs/tags/ippcp_2021.8.tar.gz] to /root/.cache/bazel/_bazel_root/e58a711e46c6fe6f1f5547f91562fb00/external/com_github_intel_ipp/temp10266711606055131087/ippcp_2021.8.tar.gz: Checksum was d70f42832337775edb022ca8ac1ac418f272e791ec147778ef7942aede414cdc but wanted 1ecfa70328221748ceb694debffa0106b92e0f9bf6a484f8e8512c2730c7d730

### Standalone code to reproduce the issue

```Python
在执行bazel build //... -c opt，提示无法获取到intel ipp库有问题，在centos和anolis os两个服务器中，均出现这个问题。
```

**Comment by tpppppub** [comment] 2024-11-06 02:44
duplicate of #889

**Closed** 2024-11-06 03:02 UTC
