### ISSUE TITLE
bazel build //examples/cpp:simple_lr 编译错误

### ISSUE THREAD

**Issue by xiaolangde** [secretflow/spu#356] opened 2023-09-18 13:49 UTC
```
In file included from external/yacl/yacl/crypto/utils/rand.h:27,

                 from external/yacl/yacl/crypto/utils/rand.cc:15:
external/yacl/yacl/base/dynamic_bitset.h: In instantiation of 'constexpr yacl::dynamic_bitset<Block, Allocator>::dynamic_bitset(yacl::dynamic_bitset<Block, Allocator>::size_type, uint128_t, const allocator_type&) [with Block = __int128 unsigned; Allocator = std::allocator<__int128 unsigned>; yacl::dynamic_bitset<Block, Allocator>::size_type = long unsigned int; uint128_t = __int128 unsigned; yacl::dynamic_bitset<Block, Allocator>::allocator_type = std::allocator<__int128 unsigned>]':
external/yacl/yacl/crypto/utils/rand.cc:156:1:   required from here
external/yacl/yacl/base/dynamic_bitset.h:2294:20: error: division by zero is not a constant expression
 2294 |   constexpr size_t init_val_required_blocks = u128_bits_number / bits_per_block;
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~
Target //examples/cpp:simple_lr failed to build
```

**Comment by anakinxc** [comment] 2023-09-18 14:47
Duplicate of https://github.com/secretflow/yacl/issues/121

**Comment by xiaolangde** [comment] 2023-09-19 03:02
感谢@anakinxc ，已参考https://github.com/secretflow/yacl/issues/121 更新gcc解决
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update && sudo apt install gcc-11 g++-11 cpp-11
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-11 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-11 
sudo update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-11 110 
```

**Closed** 2023-09-19 05:02 UTC
